language: objective-c

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8.3
script: xcodebuild build -workspace iMedia.xcworkspace -scheme iMedia CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM="" CODE_SIGNING_REQUIRED=NO
